# Generated by Django 3.2.25 on 2024-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voiceID', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('agentType', models.CharField(default='default_type', max_length=255)),
                ('documentType', models.CharField(max_length=255)),
                ('prompt', models.CharField(max_length=100000)),
                ('info', models.JSONField()),
            ],
        ),
    ]
