# Generated by Django 3.2.25 on 2024-07-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_gender_agent_voiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
