# Generated by Django 3.2.25 on 2024-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20240703_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Objectives',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='Products',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='Rules',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='policies',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
