# Generated by Django 3.2.25 on 2024-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='conversation_id',
            new_name='call_id',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='call_ended',
            new_name='end_at',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_started',
        ),
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='call',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='call',
            name='agent_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='analysis_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='answered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='c_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='call_ended_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='call_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='call_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='concatenated_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='corrected_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='endpoint_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='from_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='inbound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='local_dialing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='max_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='pathway_logs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='queue_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='to_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='transcripts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='transferred_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
