# Generated by Django 3.2.25 on 2024-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20240628_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='agent_id',
            field=models.IntegerField(default=0),
        ),
    ]
