# Generated by Django 3.2.25 on 2024-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_call_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='inbound',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
