# Generated by Django 3.2.25 on 2024-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_alter_call_inbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='local_dialing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
