# Generated by Django 3.2.25 on 2024-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_alter_call_local_dialing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='record',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
