# Generated by Django 3.2.25 on 2024-07-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='added_date',
            new_name='addedDate',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
